// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { migrationDatabaseUrl } from "./src/lib/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // NOT process.env.DATABASE_URL — migrations need the direct endpoint,
    // not Neon's pooler. See the comment in src/lib/database-url.ts.
    url: migrationDatabaseUrl(),
  },
});
